# Generated by Django 6.0.5 on 2026-05-11 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TacticalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_focus', models.CharField(choices=[('own', 'Juego propio'), ('opponent', 'Rival')], default='own', max_length=10)),
                ('system_used', models.CharField(blank=True, max_length=20)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('recurring_errors', models.TextField(blank=True)),
                ('coach_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tactical_reports', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactical_reports', to='matches.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactical_reports', to='clubs.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TacticalPhaseObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('build_up', 'Salida de balón'), ('attack', 'Ataque posicional'), ('defense', 'Organización defensiva'), ('off_transition', 'Transición ofensiva'), ('def_transition', 'Transición defensiva'), ('set_piece', 'Balón parado'), ('pressing', 'Presión')], max_length=20)),
                ('minute_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('minute_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pattern_detected', models.CharField(max_length=200)),
                ('effectiveness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_observations', to='tactical.tacticalreport')),
            ],
            options={
                'ordering': ['report', 'phase', 'minute_start'],
            },
        ),
    ]
