# Generated by Django 6.0.5 on 2026-05-12 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_confederation_club_entity_type_club_fifa_code_and_more'),
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerseasonstat',
            options={'ordering': ['-season__start_date', 'player__last_name']},
        ),
        migrations.AlterUniqueTogether(
            name='playerseasonstat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='competition',
            field=models.ForeignKey(blank=True, help_text='Competición específica si quieres separar liga, copa, mundial, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_season_stats', to='clubs.competition'),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Equipo con el que se registran estas estadísticas en esa temporada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_season_stats', to='clubs.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(blank=True, help_text='Equipo habitual/actual del jugador. No sustituye convocatorias temporales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='clubs.team'),
        ),
        migrations.AlterUniqueTogether(
            name='playerseasonstat',
            unique_together={('player', 'season', 'team', 'competition')},
        ),
        migrations.CreateModel(
            name='NationalTeamCallUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('squad_role', models.CharField(blank=True, help_text='Ej.: titular, suplente, prelista, reserva.', max_length=50)),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_up_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_callups', to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='national_callups', to='clubs.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_callups', to='players.player')),
                ('team', models.ForeignKey(limit_choices_to={'team_type__in': ['national', 'youth_national', 'women_national']}, on_delete=django.db.models.deletion.CASCADE, related_name='callups', to='clubs.team')),
            ],
            options={
                'ordering': ['-start_date', 'team__name', 'player__last_name'],
            },
        ),
    ]
