# Generated by Django 6.0.5 on 2026-05-11 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MatchKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('kpi_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_values', to='kpi.kpitype')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='matches.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_kpis', to='clubs.team')),
            ],
            options={
                'ordering': ['-match__match_date'],
                'unique_together': {('match', 'team', 'kpi_type')},
            },
        ),
        migrations.CreateModel(
            name='PlayerKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('kpi_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_values', to='kpi.kpitype')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_kpis', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_kpis', to='players.player')),
            ],
            options={
                'ordering': ['-match__match_date'],
                'unique_together': {('match', 'player', 'kpi_type')},
            },
        ),
    ]
