# Generated by Django 6.0.5 on 2026-05-12 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='confederation',
            field=models.CharField(blank=True, help_text='UEFA, CONMEBOL, CONCACAF, CAF, AFC, OFC...', max_length=30),
        ),
        migrations.AddField(
            model_name='club',
            name='entity_type',
            field=models.CharField(choices=[('club', 'Club'), ('federation', 'Federación'), ('association', 'Asociación nacional'), ('academy', 'Academia'), ('other', 'Otra')], default='club', max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='fifa_code',
            field=models.CharField(blank=True, help_text='Útil para selecciones/federaciones: ESP, ARG, FRA, etc.', max_length=10),
        ),
        migrations.AddField(
            model_name='club',
            name='is_national_entity',
            field=models.BooleanField(default=False, help_text='Marca si esta organización representa una estructura nacional.'),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('league', 'Liga'), ('cup', 'Copa'), ('international_club', 'Internacional de clubes'), ('international_national', 'Internacional de selecciones'), ('friendly', 'Amistoso'), ('other', 'Otra')], default='league', max_length=30),
        ),
        migrations.AddField(
            model_name='competition',
            name='is_national_teams',
            field=models.BooleanField(default=False, help_text='Marca si la competición es de selecciones nacionales.'),
        ),
        migrations.AddField(
            model_name='competition',
            name='organizer',
            field=models.CharField(blank=True, help_text='Ej.: FIFA, UEFA, RFEF, LaLiga...', max_length=120),
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, help_text='Útil especialmente para selecciones.', max_length=60),
        ),
        migrations.AddField(
            model_name='team',
            name='fifa_ranking',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('mixed', 'Mixto')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('club', 'Equipo de club'), ('national', 'Selección nacional'), ('youth_national', 'Selección inferior'), ('women_national', 'Selección femenina'), ('academy', 'Academia'), ('other', 'Otro')], default='club', max_length=20),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='squad_label',
            field=models.CharField(blank=True, help_text='Ej.: Plantilla Mundial 2026, Plantilla Nations League, Primer equipo 2025/26.', max_length=120),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('first_team', 'Primer equipo'), ('u23', 'Sub-23'), ('u21', 'Sub-21'), ('u20', 'Sub-20'), ('u19', 'Sub-19'), ('u17', 'Sub-17'), ('u16', 'Sub-16'), ('women_first', 'Femenino primer equipo')], default='first_team', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='club',
            field=models.ForeignKey(help_text='Se mantiene el nombre del campo por compatibilidad.', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='clubs.club'),
        ),
    ]
