# Generated by Django 6.0.5 on 2026-05-11 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('tactical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='videos/matches/')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('external_url', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='matches.match')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_second', models.PositiveIntegerField()),
                ('end_second', models.PositiveIntegerField()),
                ('export_path', models.CharField(blank=True, max_length=255)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='video.videoasset')),
            ],
            options={
                'ordering': ['video', 'start_second'],
            },
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('second_mark', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('tactical_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_tags', to='tactical.tacticalphaseobservation')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='video.videoasset')),
            ],
            options={
                'ordering': ['video', 'second_mark'],
            },
        ),
    ]
