# Generated by Django 6.0.5 on 2026-05-11 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('total_distance_m', models.PositiveIntegerField(default=0)),
                ('high_speed_distance_m', models.PositiveIntegerField(default=0)),
                ('sprint_count', models.PositiveSmallIntegerField(default=0)),
                ('max_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('accel_count', models.PositiveSmallIntegerField(default=0)),
                ('decel_count', models.PositiveSmallIntegerField(default=0)),
                ('workload_index', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_loads', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_loads', to='players.player')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='WellnessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('fatigue', models.PositiveSmallIntegerField(default=0)),
                ('soreness', models.PositiveSmallIntegerField(default=0)),
                ('stress', models.PositiveSmallIntegerField(default=0)),
                ('sleep_quality', models.PositiveSmallIntegerField(default=0)),
                ('rpe', models.PositiveSmallIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_reports', to='players.player')),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('player', 'report_date')},
            },
        ),
    ]
