# Generated by Django 6.0.5 on 2026-05-11 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('opponent', 'Informe de rival'), ('postmatch', 'Informe postpartido'), ('individual', 'Informe individual'), ('tactical', 'Informe táctico'), ('executive', 'Resumen ejecutivo')], max_length=20)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('pptx', 'PowerPoint'), ('xlsx', 'Excel')], default='pdf', max_length=10)),
                ('file', models.FileField(upload_to='reports/')),
                ('summary', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='matches.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='players.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='clubs.team')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
