# Generated by Django 6.0.5 on 2026-05-11 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('finished', 'Finalizado'), ('postponed', 'Aplazado')], default='scheduled', max_length=12)),
                ('venue', models.CharField(blank=True, max_length=120)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='clubs.team')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='clubs.competition')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='clubs.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='clubs.season')),
            ],
            options={
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='MatchTeamStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('xg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('shots', models.PositiveSmallIntegerField(default=0)),
                ('shots_on_target', models.PositiveSmallIntegerField(default=0)),
                ('passes', models.PositiveSmallIntegerField(default=0)),
                ('pass_accuracy_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ppda', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recoveries', models.PositiveSmallIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='matches.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='clubs.team')),
            ],
            options={
                'ordering': ['-match__match_date'],
                'unique_together': {('match', 'team')},
            },
        ),
    ]
