# Generated by Django 6.0.5 on 2026-05-15 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_confederation_club_entity_type_club_fifa_code_and_more'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-match_date'], 'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AlterModelOptions(
            name='matchteamstat',
            options={'ordering': ['-match__match_date', 'team__name'], 'verbose_name': 'Estadística de equipo por partido', 'verbose_name_plural': 'Estadísticas de equipo por partido'},
        ),
        migrations.AlterUniqueTogether(
            name='matchteamstat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matchteamstat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchteamstat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Goles visitante'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='clubs.team', verbose_name='Equipo visitante'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Goles local'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='clubs.team', verbose_name='Equipo local'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(verbose_name='Fecha y hora del partido'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programado'), ('finished', 'Finalizado'), ('postponed', 'Aplazado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=12, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, max_length=120, verbose_name='Estadio / sede'),
        ),
        migrations.AlterField(
            model_name='matchteamstat',
            name='pass_accuracy_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Precisión de pase %'),
        ),
        migrations.AlterField(
            model_name='matchteamstat',
            name='passes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Pases'),
        ),
        migrations.AlterField(
            model_name='matchteamstat',
            name='possession_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Posesión %'),
        ),
        migrations.AlterField(
            model_name='matchteamstat',
            name='ppda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='PPDA'),
        ),
        migrations.AlterField(
            model_name='matchteamstat',
            name='recoveries',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Recuperaciones'),
        ),
        migrations.AlterField(
            model_name='matchteamstat',
            name='shots',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tiros'),
        ),
        migrations.AlterField(
            model_name='matchteamstat',
            name='shots_on_target',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tiros a puerta'),
        ),
        migrations.AlterField(
            model_name='matchteamstat',
            name='xg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='xG'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_date'], name='matches_match_date_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='matches_status_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['season', 'match_date'], name='matches_season_date_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['competition', 'match_date'], name='matches_comp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['home_team'], name='matches_home_team_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['away_team'], name='matches_away_team_idx'),
        ),
        migrations.AddIndex(
            model_name='matchteamstat',
            index=models.Index(fields=['match'], name='mts_match_idx'),
        ),
        migrations.AddIndex(
            model_name='matchteamstat',
            index=models.Index(fields=['team'], name='mts_team_idx'),
        ),
        migrations.AddIndex(
            model_name='matchteamstat',
            index=models.Index(fields=['match', 'team'], name='mts_match_team_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='matches_home_team_not_equal_away_team'),
        ),
        migrations.AddConstraint(
            model_name='matchteamstat',
            constraint=models.UniqueConstraint(fields=('match', 'team'), name='matches_unique_match_team_stat'),
        ),
    ]
